### ISSUE TITLE
Improve "Vanilla" NoFall

### ISSUE THREAD

**Issue by ed0cinU** [DietrichPaul/Winkel#9]
Instead of using the Packet Spamm default Method, be advanced and use a Packet Event where you set false to true.

(This is trash)
![image](https://user-images.githubusercontent.com/58796076/176566047-0df43e46-7453-475c-bcae-67cceb763abc.png)

**Comment by ed0cinU** [comment]
@lumii-uwu machs beim nächsten mal auch so xd

**Comment by FlorianMichael** [comment]
We recode the NoFall as soon as we make the Movement Modules.
